# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QS1EAalCLDYdxyQ_e_wHzOddChbeQg2T

##Practica PANDA 🐼
"""

import pandas as pd

ruta = "https://github.com/juanvasquez95252-max/Fundamento-de-programacion/raw/refs/heads/main/Estado_de_la_prestacion_del_servicio_de_energ%C3%ADa_en_Zonas_No_Interconectadas_202604.csv"

df = pd.read_csv(ruta)
display(df)

"""##Info

Informacion del dataset.
"""

df.info()

"""##Reporte:
- Datos faltantes
  - POTENCIA MÁXIMA ( 6216 - 6132 = 84 Faltantes)
  - DÍA DE DEMANDA MÁXIMA ( 6216 - 6131 = 85 Faltantes )
  - FECHA DE DEMANDA MÁXIMA ( 6216 - 6132 = 84 Faltante )

- Variables correctas
- Object
  - 1   DEPARTAMENTO              6216 non-null   object
  - 3   MUNICIPIO                 6216 non-null   object
  - 5   LOCALIDAD                 6216 non-null   object
  -  8   ENERGÍA ACTIVA            6216 non-null   object
  - 9   ENERGÍA REACTIVA          6216 non-null   object
  - 10  POTENCIA MÁXIMA           6132 non-null   object
  - 11  DÍA DE DEMANDA MÁXIMA     6131 non-null   object
  - 12  FECHA DE DEMANDA MÁXIMA   6132 non-null   object
  - 13  PROMEDIO DIARIO EN HORAS  6216 non-null   object

## visualizar los primeros datos

- df.head(# de tados a visualizar) incial
- df.tail(# de tados a visualizar) final
"""

df.head(5)

df.tail(5)

"""## Nombre de columnas

 df.columns
"""

df.columns

"""## Ver alguna columns

"""

df[['DEPARTAMENTO','ID DEPATAMENTO','MUNICIPIO']]

"""## Guardar la consulta o df
```
consulta = df.[['columna 1',...,'columnaN']]
consulta.to_formato(nombre_archivo.extension")
```
"""

consulta = df[['DEPARTAMENTO','ID DEPATAMENTO','MUNICIPIO']]
consulta.to_csv("Estado de energia.csv")